# Generated by Django 4.0 on 2021-12-22 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
